NumPy Library  :- NumPy is a library in Python that helps you work with arrays and perform mathematical operations quickly and easily.

In [110]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [111]:
import numpy as np
arr=[7,8,9,10]
arr=np.array(arr)
print(arr)

[ 7  8  9 10]


In [112]:
arr_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(arr_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [113]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [115]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [116]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [117]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [119]:
np.linspace(5,20,10)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [120]:
np.linspace(7,20,30)

array([ 7.        ,  7.44827586,  7.89655172,  8.34482759,  8.79310345,
        9.24137931,  9.68965517, 10.13793103, 10.5862069 , 11.03448276,
       11.48275862, 11.93103448, 12.37931034, 12.82758621, 13.27586207,
       13.72413793, 14.17241379, 14.62068966, 15.06896552, 15.51724138,
       15.96551724, 16.4137931 , 16.86206897, 17.31034483, 17.75862069,
       18.20689655, 18.65517241, 19.10344828, 19.55172414, 20.        ])

In [121]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
np.random.rand(5)

array([0.0058351 , 0.31770121, 0.27093884, 0.23853125, 0.59750938])

In [123]:
np.random.rand()

0.5953608655455119

In [124]:
np.random.rand(2,4)

array([[0.13089968, 0.10680365, 0.16133776, 0.52055352],
       [0.62095301, 0.79302681, 0.02486976, 0.98945801]])

In [125]:
np.random.rand(7,9)

array([[0.59649084, 0.43833773, 0.46957302, 0.20780081, 0.73045527,
        0.95748552, 0.03617992, 0.66856324, 0.03706113],
       [0.75273127, 0.41144436, 0.82140572, 0.80902441, 0.49687234,
        0.73541367, 0.90348494, 0.79858065, 0.31103178],
       [0.36457453, 0.46634205, 0.66487927, 0.85175977, 0.04648078,
        0.58700371, 0.94389938, 0.7882624 , 0.63722765],
       [0.11626492, 0.52024933, 0.04611417, 0.81805532, 0.08078486,
        0.89490667, 0.79310323, 0.94778175, 0.34854655],
       [0.41563952, 0.57550785, 0.15719184, 0.65587455, 0.29774352,
        0.05368162, 0.96690518, 0.81686406, 0.32780316],
       [0.53510752, 0.51271569, 0.66972412, 0.9052044 , 0.06929473,
        0.73225167, 0.22898958, 0.43380175, 0.52965094],
       [0.12900387, 0.70788755, 0.23425847, 0.57642914, 0.82216799,
        0.12144785, 0.34261553, 0.62741444, 0.58664344]])

In [126]:
np.random.randint(9)

2

In [127]:
np.random.randint(1,9)

4

In [128]:
np.random.randint(4,66,7)

array([34, 64,  8, 21, 33, 42, 58])

In [129]:
np.random.randint(10,31,size=5)

array([14, 29, 28, 16, 22])

In [130]:
arrval=np.arange(25)
arrval

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [131]:
arr=np.array([10,20,30,40,50])
arr.reshape(5,1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [132]:
arr=np.arange(25)
np.random.rand(1,5,6)

array([[[0.89603328, 0.59510678, 0.12217502, 0.18317989, 0.97904117,
         0.90624346],
        [0.83408899, 0.60900608, 0.12944941, 0.08425678, 0.36409001,
         0.61013263],
        [0.24695106, 0.25214931, 0.43724401, 0.635357  , 0.35280133,
         0.06107922],
        [0.12456743, 0.93510561, 0.22191928, 0.29167013, 0.47891778,
         0.29715097],
        [0.42803614, 0.00921254, 0.48254465, 0.13482449, 0.60172692,
         0.02652517]]])

In [133]:
np.random.randn(6)

array([-0.2618132 , -0.38589733,  1.24689058, -0.95115102, -0.68340641,
       -0.46793484])

In [134]:
arr=np.arange(50)
ranarr=np.random.randint(10,50,20)
ranarr

array([34, 25, 41, 24, 29, 42, 48, 16, 45, 16, 29, 48, 44, 16, 30, 12, 13,
       42, 39, 14])

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [136]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [137]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [138]:
arr.max()

49

In [139]:
arr.min

<function ndarray.min>

In [140]:
arr.min()

0

In [141]:
arr.argmin()

0

In [142]:
arr.argmax

<function ndarray.argmax>

In [143]:
arr.argmax()

49

In [144]:
arr.shape

(50,)

In [145]:
arr.reshape(50,1).shape

(50, 1)

In [146]:
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [147]:
arr.reshape(25,2).shape

(25, 2)

In [148]:
arr.dtype

dtype('int32')

In [149]:
arr=np.array(25,dtype=float)
arr

array(25.)

In [150]:
arr.dtype

dtype('float64')

In [151]:
arr=np.array(45,dtype=bool)
arr

array(True)

In [152]:
arr.dtype

dtype('bool')

In [153]:
arr=np.array(67,dtype=int)
arr.dtype

dtype('int32')

In [154]:
arr

array(67)

In [155]:
arr=np.array(10)
arr

array(10)

In [156]:
arr=np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [157]:
add_arr=arr+5
add_arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [158]:
mul_arr=arr*2
mul_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [159]:
arr_dot=np.dot(arr,arr.T)
arr_dot

40425

In [160]:
arr_first=arr[0]
arr_first

0

In [161]:
arr_last=arr[49]
arr_last

49

In [162]:
arr_25=arr[24]
arr_25

24

In [163]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [164]:
secondrow=arr_2d[1:2]
secondrow

array([[4, 5, 6]])

In [165]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [166]:
mean=np.mean(arr)
mean

24.5

In [167]:
sd=np.std(arr)
sd

14.430869689661812

In [168]:
gt_than_3=arr>3
gt_than_3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [169]:
v_stack=np.vstack(arr)
v_stack

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

In [170]:
h_stack=np.hstack(arr)
h_stack

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [171]:
arr_Tranpose=arr.T
arr_Tranpose

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [172]:
arr1=np.array([10,20,30,40,50,55])
arr2=np.array([60,70,80,90,100,105])
arr=np.concatenate((arr1,arr2))
arr

array([ 10,  20,  30,  40,  50,  55,  60,  70,  80,  90, 100, 105])

In [173]:
reshape1=np.concatenate((arr1.reshape(1,6),arr2.reshape(1,6)))
reshape1

array([[ 10,  20,  30,  40,  50,  55],
       [ 60,  70,  80,  90, 100, 105]])

In [174]:
reshape2=np.concatenate((arr1.reshape(6,1),arr2.reshape(6,1)))
reshape2

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 55],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100],
       [105]])

In [175]:
import numpy as np

In [176]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
arr[8]

8

In [178]:
arr[5:9]

array([5, 6, 7, 8])

In [179]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [180]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
arr[:6]=90
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9])

In [182]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
arr_copy=arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
arr_copy_val=arr.copy()
arr_copy_val[:]=78
arr_copy_val


array([78, 78, 78, 78, 78, 78, 78, 78, 78, 78])

In [188]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [190]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [191]:
np.max(arr)

9

In [192]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [193]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [194]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [195]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [196]:
arr=np.log(arr)
arr

C:\Users\Ankita Ghavate\AppData\Local\Temp\ipykernel_7296\2095848443.py:1: RuntimeWarning: divide by zero encountered in log
  arr=np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [197]:
arr

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [198]:
arr = np.array([1, 3, 3, 6, 7, 8, 9])
np.median(arr)

6.0

**Thank You..!!!**